#!/usr/bin/env python

from configparser import ConfigParser, ExtendedInterpolation
from blk import Pipeline, TaskParallelPipeline, SegmentParallelPipeline
import sys
from os.path import abspath

if __name__ == "__main__":
    config_file = abspath(sys.argv[1])

    config = ConfigParser(
        allow_no_value=True, 
        interpolation=ExtendedInterpolation())

    # prevents configparser from lowercasing everything
    config.optionxform = str
    config.read(config_file)

    if config["blk"]["parallel"] == "task":
        pipe = TaskParallelPipeline(config_file)
    elif config["blk"]["parallel"] == "segment":
        pipe = SegmentParallelPipeline(config_file)
    else:
        pipe = Pipeline(config_file)

    pipe.run()

    