MAX_SEGMENTS = 10000

TASK_ACTION_OPTIONS = ["auto", "manual"]
AUTO, MANUAL = TASK_ACTION_OPTIONS

TASK_STATUS_OPTIONS = ["complete", "skipped", "failed"]
COMPLETE, SKIP, FAIL = TASK_STATUS_OPTIONS

DEPENDENCY_STRATEGIES = ["one-to-one", "all", "none"]
ONE_TO_ONE, ALL, NONE = DEPENDENCY_STRATEGIES

ITERATION_LIMIT = int(1e6)